apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  namespace: learner-report-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: learner-report-backend
        image: reshmanavale/learnerreportbe:v1.1
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: ATLAS_URI
          valueFrom:
            secretKeyRef:
              name: be-secret
              key: ATLAS_URI