apiVersion: v1
kind: Secret
metadata:
  name: be-secret
  namespace: learner-report-backend
type: Opaque
data:
  #MONGO_URI: mongodb://db-service.learner-report-db.svc.cluster.local:27017
  ATLAS_URI: bW9uZ29kYjovL3Jlc2htYTpyZXNobWFAZGItc2VydmljZS5sZWFybmVyLXJlcG9ydC1kYi5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNw==
