apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: learner-report-db
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP