apiVersion: v1
kind: Secret
metadata:
  name: fe-secret
  namespace: learner-report-frontend
type: Opaque
data:
  REACT_APP_BACKEND_URL: aHR0cDovL2E0Y2U1Y2JkYmJkNjY0ZDFjYTgwNmI0ZmFlYWYwYjdiLTIwMTE2MjU2NDIudXMtd2VzdC0xLmVsYi5hbWF6b25hd3MuY29tOjMwMDE=

  #http://be-service.learner-report-db.svc.cluster.local:3001
  #aHR0cDovL2JlLXNlcnZpY2UubGVhcm5lci1yZXBvcnQtZGIuc3ZjLmNsdXN0ZXIubG9jYWw6MzAwMQ==
  

